language: node_js
node_js:
  - 14
script:
  - yarn
  - yarn build
deploy:
  provider: heroku
  api_key: $Heroku__App__Key
  app: estimation-tool-ui
  on:
    branch: develop
notifications:
  slack: estimationtool:$Slack__Key
