language: node_js
node_js:
  - 14
script:
  - yarn
  - yarn build
notifications:
  slack: estimationtool:bOTvxHaF5GBvP2e6Q2gErCqr
deploy:
  provider: heroku
  api_key: ad2bc513-3a3c-42f1-a2cd-1233c117652e
  app: estimation-tool-ui
  on:
    branch: develop
