language: node_js
node_js:
  - 14
script:
  - yarn
  - yarn build
notifications:
  slack: estimationtool:bOTvxHaF5GBvP2e6Q2gErCqr
deploy:
  provider: heroku
  api_key: 0a5c485f-5dc8-4085-bbe2-6bb920ed3208
  app: estimation-tool-ui
  on:
    branch: develop
